## Arquivo Acidentes Londres

**Passo a passo para a analise**

- Importando as Libs necessárias
- Conhecendo os dados

In [1]:
# Import das libs
import numpy as np
import pandas as pd

In [2]:
# Fazendo a leitura do arquivo que puxaremos as informações
acidentes = pd.read_csv('Acidentes.csv', low_memory=False)

In [3]:
# Conhecendo o conjunto de dados
acidentes.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,197901A11AD14,NaN,NaN,NaN,NaN,1,3,2,1,18/01/1979,...,-1,-1,1,8,1,-1,0,-1,-1,NaN
1,197901A1BAW34,198460.0,894000.0,NaN,NaN,1,3,1,1,01/01/1979,...,-1,-1,4,8,3,-1,0,-1,-1,NaN
2,197901A1BFD77,406380.0,307000.0,NaN,NaN,1,3,2,3,01/01/1979,...,-1,-1,4,8,3,-1,0,-1,-1,NaN
3,197901A1BGC20,281680.0,440000.0,NaN,NaN,1,3,2,2,01/01/1979,...,-1,-1,4,8,3,-1,0,-1,-1,NaN
4,197901A1BGF95,153960.0,795000.0,NaN,NaN,1,2,2,1,01/01/1979,...,-1,-1,4,3,3,-1,0,-1,-1,NaN

In [4]:
print('Total de linhas: {}'.format(len(acidentes)))

Total de linhas: 6224198

In [5]:
# Observar os headers
print(list(acidentes))

['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control', '2nd_Road_Class', '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident', 'LSOA_of_Accident_Location']

In [7]:
print('-----------------------------------------')
print('Acidentes no Reino Unido de 1979 até 2004')
print('-----------------------------------------')

# Acidentes que ocorreram no Domingo
domingo = acidentes[acidentes.Day_of_Week == 1]
print('Acidentes que ocorreram no domingo: {}'.format(len(domingo)))

-----------------------------------------
Acidentes no Reino Unido de 1979 até 2004
-----------------------------------------
Acidentes que ocorreram no domingo: 693847